site_name: tdx
site_description: Create a website for owner of online store so they can put all their information here
repo_url: https://github.com/vebr/Tokodex
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/vebr">vebr</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
